function [thisCValue]= functionC(option,thisStepSpace,currSpot,currTime) 
thisCValue=0.25*(option.Vol*option.Vol*thisStepSpace*thisStepSpace+...
    (option.InterestRate-option.divident)*thisStepSpace)*(option.Expiry*1.0/option.timeStep);