function [thisBValue]= functionB(option,thisStepSpace,currSpot,currTime) 
thisBValue=-0.5*(option.Vol*option.Vol*thisStepSpace*thisStepSpace+...
    option.InterestRate)*(option.Expiry*1.0/option.timeStep);